<<<<<<< HEAD
# Generated by Django 5.2.7 on 2026-01-19 10:13
=======
# Generated by Django 5.2.8 on 2026-01-18 15:35
>>>>>>> 13442e257a256d8cee4996614c7023cc184b02ff

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articolo',
            options={'verbose_name': 'Articolo', 'verbose_name_plural': 'Articoli'},
        ),
        migrations.AlterModelOptions(
            name='giornalista',
            options={'verbose_name': 'Giornalista', 'verbose_name_plural': 'Giornalisti'},
        ),
    ]
